### PR TITLE
Add work-break to hashes. Rebuild CSS source and tooling

### PR DESCRIPTION
**Pull request by MattyBalaam**
https://github.com/profanity-im/profanity-im.github.io/issues/33

I’ve done a quick rough first pass at this replacing the tooling and updating the css source files. I have removed some libraries which provided automation of creating some size variables but have just copy/pasted from the compiled css.

I did some very brief looking around but not a thorough check. It might be good to give a little look over to see if any styles have been broken.

### CODE REVIEW

**Comment by jubalh** [comment]
Cool! Thanks!

**Comment by MattyBalaam** [comment]
Should be able to look before the weekend at this

**Comment by MattyBalaam** [comment]
Header link colours should now be fixed.

**Comment by jubalh** [comment]
Thanks @MattyBalaam !

**Pull request merged**
